import type { DecisionTrail } from './types';

import { app } from './configs';

/**
 * Get max characters from config
 */
function getMaxChars(): number {
  const cfg = app();
  return cfg.maxTokenBudget * cfg.charsPerToken;
}

/**
 * Build a structured prompt from the decision trail
 */
export function buildContext(trail: DecisionTrail): string {
  const sections: string[] = [];

  // Header
  sections.push('# Code Decision Trail');
  sections.push('');
  sections.push(
    'You are analyzing why a specific piece of code exists. Below is all the context we could gather from git history, PRs, and issues.',
  );
  sections.push('');

  // Commit info
  sections.push('## Git Commit');
  sections.push(`- **SHA**: ${trail.blame.sha}`);
  sections.push(`- **Author**: ${trail.blame.authorName} <${trail.blame.authorEmail}>`);
  sections.push(`- **Date**: ${trail.blame.authorDate.toISOString()}`);
  sections.push('');
  sections.push('### Commit Message');
  sections.push('```');
  sections.push(truncate(trail.blame.commitMessage, 500));
  sections.push('```');
  sections.push('');

  // Diff
  sections.push('### Diff (changes introduced)');
  sections.push('```diff');
  sections.push(truncate(trail.blame.diff, 2000));
  sections.push('```');
  sections.push('');

  // PR context if available
  if (trail.pr) {
    sections.push('## Pull Request');
    sections.push(`- **PR #${trail.pr.number}**: ${trail.pr.title}`);
    sections.push(`- **State**: ${trail.pr.state}`);
    if (trail.pr.labels.length > 0) {
      sections.push(`- **Labels**: ${trail.pr.labels.join(', ')}`);
    }
    sections.push('');

    if (trail.pr.body) {
      sections.push('### PR Description');
      sections.push(truncate(stripAutoGeneratedContent(trail.pr.body), 1500));
      sections.push('');
    }

    // Review comments (inline code comments)
    if (trail.pr.reviewComments.length > 0) {
      sections.push('### Code Review Comments');
      for (const comment of trail.pr.reviewComments.slice(0, 10)) {
        sections.push(
          `**${comment.user}** on \`${comment.path}${comment.line ? `:${comment.line}` : ''}\`:`,
        );
        sections.push(`> ${truncate(comment.body, 300).replace(/\n/g, '\n> ')}`);
        sections.push('');
      }
    }

    // General PR comments
    if (trail.pr.comments.length > 0) {
      sections.push('### PR Discussion');
      for (const comment of trail.pr.comments.slice(0, 5)) {
        sections.push(
          `**${comment.user}**${comment.reactions > 0 ? ` (${comment.reactions} reactions)` : ''}:`,
        );
        sections.push(`> ${truncate(comment.body, 300).replace(/\n/g, '\n> ')}`);
        sections.push('');
      }
    }
  } else {
    sections.push('## Pull Request');
    sections.push(
      '*No PR found for this commit. It may have been pushed directly to the main branch.*',
    );
    sections.push('');
  }

  // Linked issues
  if (trail.issues.length > 0) {
    sections.push('## Linked Issues');
    for (const issue of trail.issues.slice(0, 3)) {
      sections.push(`### Issue #${issue.number}: ${issue.title}`);
      sections.push(`- **State**: ${issue.state}`);
      if (issue.labels.length > 0) {
        sections.push(`- **Labels**: ${issue.labels.join(', ')}`);
      }
      sections.push('');
      if (issue.body) {
        sections.push('**Description:**');
        sections.push(truncate(stripAutoGeneratedContent(issue.body), 800));
        sections.push('');
      }
      if (issue.comments.length > 0) {
        sections.push('**Key Comments:**');
        for (const comment of issue.comments.slice(0, 3)) {
          sections.push(
            `- **${comment.user}**: ${truncate(comment.body, 200).replace(/\n/g, ' ')}`,
          );
        }
        sections.push('');
      }
    }
  }

  // Build and trim to budget
  let result = sections.join('\n');
  const maxChars = getMaxChars();
  if (result.length > maxChars) {
    result = result.slice(0, maxChars) + '\n\n... (context truncated to fit token budget)';
  }

  return result;
}

/**
 * Build the system prompt for Claude
 */
export function buildSystemPrompt(): string {
  return `You are analyzing legacy code to explain WHY it exists and the decisions behind it.

Your task is to synthesize the provided context (git commit, PR, issues, comments) into a clear, concise explanation.

Guidelines:
1. Write 3-5 sentences maximum
2. Focus on the "why" - what problem was this solving?
3. Mention any alternatives that were considered (if visible in discussions)
4. Note any gotchas or edge cases the author mentioned
5. If the context is sparse, say what you can infer and acknowledge limitations
6. Never make up information - only use what's in the context
7. Be direct and useful for a developer trying to understand this code

Format:
- Start with the core reason for the change
- Then add supporting details from discussions
- End with any warnings or gotchas if relevant`;
}

/**
 * Truncate text to a maximum length
 */
function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength - 3) + '...';
}

/**
 * Strip auto-generated content from PR/issue bodies
 */
function stripAutoGeneratedContent(text: string): string {
  // Remove common auto-generated sections
  const patterns = [
    // GitHub PR templates
    /<!--[\s\S]*?-->/g,
    // Copilot/AI summaries
    /### Summary by (?:CodeRabbit|Codeflash|Copilot)[\s\S]*?(?=\n#{1,3} |$)/gi,
    // Dependabot release notes
    /<details>[\s\S]*?<\/details>/g,
    // Changelog entries
    /^## Changelog[\s\S]*?(?=\n## |$)/gm,
  ];

  let result = text;
  for (const pattern of patterns) {
    result = result.replace(pattern, '');
  }

  // Clean up extra whitespace
  result = result.replace(/\n{3,}/g, '\n\n').trim();

  return result;
}

/**
 * Get the full context as a string (for --verbose mode)
 */
export function getVerboseContext(trail: DecisionTrail, builtContext: string): string {
  const sections: string[] = [];

  sections.push('═══════════════════════════════════════════════════════════════');
  sections.push('                        FULL CONTEXT TRAIL');
  sections.push('═══════════════════════════════════════════════════════════════');
  sections.push('');
  sections.push(`Repository: ${trail.repoOwner}/${trail.repo}`);
  sections.push(`Commit: ${trail.blame.sha}`);
  sections.push(`PR: ${trail.pr ? `#${trail.pr.number}` : 'None found'}`);
  sections.push(
    `Issues: ${trail.issues.length > 0 ? trail.issues.map((i) => `#${i.number}`).join(', ') : 'None found'}`,
  );
  sections.push('');
  sections.push('───────────────────────────────────────────────────────────────');
  sections.push('                    PROMPT SENT TO CLAUDE');
  sections.push('───────────────────────────────────────────────────────────────');
  sections.push('');
  sections.push(builtContext);
  sections.push('');
  sections.push('═══════════════════════════════════════════════════════════════');

  return sections.join('\n');
}
